base_config = {
    "eval_interval": 1,
    "ema_rate": 0.9999,
    "get_prompt": False,
    "split": True,
    "csv_keys": ["Name", "Prompt", "Mean IoU", "Mean F1", "Mean Accuracy", "Mean Sensitivity", "iters", "loss"],
    "opt": {
        "learning_rate": 1e-4,
        "weight_decay": 1e-4,
        "decay_factor": 10,
        "steps": [60000, 86666],
        "warmup_steps": 250,
    },
    "corruptions": [
        "gaussian_noise",
        "shot_noise",
        "impulse_noise",
        "defocus_blur",
        "glass_blur",
        "motion_blur",
        "zoom_blur",
        "snow",
        "frost",
        "fog",
        "brightness",
        "contrast",
        "elastic_transform",
        "pixelate",
        "jpeg_compression",
    ],
    "model": {
        "type": "vit_b",
        "checkpoint": "./checkpoints/",
        "ckpt": "",
        "freeze": {
            "image_encoder": True,
            "prompt_encoder": True,
            "mask_decoder": True,
        },
    },
    "datasets": {
        "phantom": {
            "train_real": "./data/train/image",
            "test_real": "./data/test/image",
        },
    },
}